PRO-428 Don't install non-MPL Terraform

diff --git a/install-terraform-version b/install-terraform-version
--- a/install-terraform-version
+++ b/install-terraform-version
@@ -5,6 +5,11 @@ set -u
 set -o pipefail
 
 VERSION="$1"
+VERSION_CHECK=${VERSION//./}
+if [ "$VERSION_CHECK" -ge "160" ]; then
+  echo "ERROR: This version of Terraform is not allowed (BUSL). Exiting."
+  exit 1
+fi
 
 if [[ "$VERSION" == "latest" ]]; then
     VERSION="${DEFAULT_TERRAFORM_VERSION}"
